### ISSUE TITLE
manifest google sheet names are different 

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/HTAN_data_curator#69]
When there is an existing manifest for the dataset, the name contains "_". Otherwise, it does not. Also, do you want to consider adding the date as part of the file name? It might be useful for some people.

**Comment by xdoan** [comment]
I removed the "_". Would it be useful to @xindiguo to have the date? The name is already so long I am hesitant to add more.

**Comment by milen-sage** [comment]
You can provide the manifest title as a parameter to the backend. We could include a config var for the manifest - e.g. title_prefix/postfix in config.py that can just be set to date, date.today() - for Xindi's use case and doesn't conflict with others' title use cases?

**Comment by xdoan** [comment]
Yeah its just a question if its useful or not, I don't think it would conflict and technically ppl can rename the file to whatever they want.
