### ISSUE TITLE
Add attribution/credits options to app

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/HTAN_data_curator#88]
suggested by @allaway to possibly add credits to data curator app(s) should have a nod to the fact that all this infrastructure is thanks to the htan grant + people and have a message such as `Supported by the Human Tumor Atlas Network (NCI grant number) Powered by Sage Bionetworks `

Possible implementations
- shinyDashboardPlus has a dashboardFooter
- sticky footer https://stackoverflow.com/questions/37113739/shiny-dashboard-sticky-footer-in-dashboardsidebar

**Comment by allaway** [comment]
A follow on idea would be to add in a configurable field (from config.yml) to allow each community to also mention the community-specific funders (since they are funding us to build the schemas ;) )

**Comment by vpchung** [comment]
Just to follow up on this --
I added a footer to ROCC's version of Data Curator using the following code:

**app.R**
```r
 42   dashboardSidebar(
 43     width = 260,
 44     tags$style(
 45       ".left-side, .main-sidebar {padding-top: 80px; font-weight: bold; font-size: 1.1em }
 46        footer{position: absolute; padding: 18px; left:0; bottom: 0; width: 100%; background-color: #D0D6DC; color: #465362; font-size: 10px; z-index: 1000;}"
 47     ),
 ...
 ...
 56     HTML('<footer>
 57         Supported by the Human Tumor Atlas Network <br/>
 58         Powered by Sage Bionetworks
 59       </footer>')
 60   ),
```

Looks like this:

<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/9377970/94346809-02091f00-ffe4-11ea-8a27-cd0d82c0a709.png">

Still learning Shiny so if there is a cleaner way of adding CSS, please edit as you please!

**Comment by xdoan** [comment]
added with #90
