### ISSUE TITLE
put loading gif on transparent background

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/HTAN_data_curator#95]
I think @vpchung made this: https://github.com/Sage-Bionetworks/HTAN_data_curator/blob/shiny-server-1.0.0.rc1/www/loading.gif

Any chance it could be placed on a transparent background so it's easier to use with other palettes?

Thanks!

**Comment by vpchung** [comment]
I can look into it!

I remember there being a reason I didn't use a transparent background though (like it just didn't look right), but maybe there's another app I can use besides Animizer in that case.

**Comment by vpchung** [comment]
Hm, doesn't look great......

![synapse_load](https://user-images.githubusercontent.com/9377970/96300809-0ef9ac80-0fab-11eb-9eb0-06496600ed76.gif)

**Comment by vpchung** [comment]
Hmm, doesn't look great ):

![synapse_load](https://user-images.githubusercontent.com/9377970/96301058-7879bb00-0fab-11eb-802e-1517ce053523.gif)

source: [loading.io](https://loading.io/animation/icon/)

**Comment by xdoan** [comment]
hahah maybe you can say that pixel art is making a comeback (I mean look at MIT's new logo) but @allaway what do you think for your use case?

**Comment by allaway** [comment]
Hahaha. I feel like i've stepped back in time https://media3.giphy.com/media/Ve4nPkjRT5avBu0qRG/giphy.gif

Maybe a better solution would be for me to just make a gif using animizer with our background hex color! Can you share the source img you used?
